config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'sign-up', to: 'registrations#new'
  post 'sign-up', to: 'registrations#create'
  get 'sign-in', to: 'authentication#new'
  post 'sign-in', to: 'authentication#create'
  get 'sign-out', to: 'authentication#destroy'



  resources :users do
    resources :gardens do
    resources :notes
    end
  end
end

app/models/garden.rb
class Garden < ActiveRecord::Base
  belongs_to :user
  has_many :notes, dependent: :destroy
end

app/models/note.rb
class Note < ActiveRecord::Base

  belongs_to :garden

end

app/models/user.rb
class User < ActiveRecord::Base
   has_secure_password

   has_many :gardens, dependent: :destroy
   has_many :notes, through: :gardens
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user


    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id].present?
    end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def new
end

  def create
  user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_gardens_path(user)
    else
      flash[:success] = "No digs! That's not a real email and password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController

  def index
    if session[:user_id] = current_user.id
      @gardens = current_user.gardens
    end
  end

  def new
    @garden = Garden.new
  end


  def create
  @garden = current_user.gardens.new(garden_params)
  if @garden.save
     redirect_to user_gardens_path(current_user, @garden)
  else
    render :new
  end
end

  def show
    @garden = Garden.find(params[:id])
    @note = Note.new
  end

  private
  def garden_params

    params.require(:garden).permit(:season_name)
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  before_action do
    @garden = Garden.find(params[:garden_id])
  end

  def create
    @note = @garden.notes.new(note_params)
    @note.save
    redirect_to user_garden_path(@garden, @garden[:id])
  end
end



private

  def note_params
    params.require(:note).permit(:title, :note, :date, :garden_id)
  end

   def find_user
     @user = User.find(current_user)
   end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:email, :password, :first_name, :last_name))
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Thanks for signing up!"
      redirect_to user_gardens_path(@user)
    else
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def current_user
    if
      session[:user_id].present?
      User.find(session[:user_id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentication/new.html.erb
<%= form_tag sign_in_path do %>

<div class="col-sm-12">
  <div class="well col-md-5 col-sm-offset-3">
    <div class="form-group">
      <h2 class = "page-header">Lets Get Growing!</h2>

<div class="form-horizontal">

   <div class="form-group"></div>
     <%= label_tag :email, "Email", class: "pull-left control-label" %>
     <div class="col-md-4"></div>
      <%= email_field_tag :email,"", autofocus: true, class: "col-sm-12 form-control" %>



   <div class="form-group"></div>
     <%= label_tag :password,"Password", class: "pull-left control-label" %>
     <div class="col-md-4"></div>
      <%= password_field_tag :password,"",class: "col-sm-12 form-control" %>



           <div class="form-group">
             <div class="col-sm-6 pull-left"><br>
               <%= submit_tag "Sign In", class: "btn btn-default"%>
             </div>
           </div>

      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/gardens/edit.html.erb
user garden edit page

app/views/gardens/index.html.erb
<div class="header navbar-fixed-top">

   <h3><%="Welcome, #{current_user.first_name.titleize}! things are growing great!" %></h3>
    <ul class="nav navbar-nav pull-right">
     <li><%= link_to "Sign Out", sign_out_path %></li>
     <li><%= link_to "New Digs", new_user_garden_path %></li>
    </ul>
</div>


<% @gardens.each do |garden| %>
  <div class="top-buffer">
    <div class="well col-md-4">
      <div class="col-md-12 text-center">
        <%= link_to garden.season_name, user_garden_path(current_user, garden) %>
      </div>
    </div>
  </div>
<% end %>

app/views/gardens/new.html.erb
<div class="header navbar-fixed-top">
   <h3><%="What will you name your garden?" %></h3>
    <ul class="nav navbar-nav pull-right">
     <li><%= link_to "Sign Out", sign_out_path %></li>
     <li><%= link_to "New Digs", new_user_garden_path %></li>
    </ul>
</div>


<div class="container">
  <div class="well top-buffer2 col-md-6 col-md-offset-1">
    <div class="form-group Welcome-index-font">

         <%= form_for([current_user, @garden], html: {class: 'form-horizontal'}) do |f| %>

        <div class= 'form-group'>
          <div class= "row">
             <%= f.label :season_name, "garden name", class: 'col-sm-3 control-label'%>
            <div class= 'col-md-8'>
              <%= f.text_field :season_name, autofocus: :true, placeholder: "enter the name of a lovely garden", class: 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <div class= "row">
            <div class= "margin-left">
              <div class="col-md-12 top-padding">
               <%= f.submit "Create", class: "signUpP", class: "btn btn-default" %>
              </div>
            </div>
          </div>


        <% end %>

    </div>
  </div>
</div>

app/views/gardens/show.html.erb
<div class="header navbar-fixed-top">
   <h3><%="#{current_user.first_name}'s garden notes" %></h3>
    <ul class="nav navbar-nav pull-right">
     <li><%= link_to "Sign Out", sign_out_path %></li>
    </ul>
</div>

<div class='container'>
    <div class="row top-buffer">
      <div class="col-md-8">
        <tr>
            <td>
            <% @garden.notes.each do |note| %>
            </td>
         </tr>
      </div>
    </div>
</div>


    <div class="notesCenter">
      <div class='container'>
        <div class="col-md-12 text-custom">
          <%= note.note %>
        </div>
      </div>

  <% end %>

    </div> <!--Close notesCenter div-->

    <div class="notesSubmit">
    <%= form_for [@garden, @note], url: user_garden_notes_path(current_user, @garden) do |f| %>
    <p>
      <div class="col-md-12">
        <%= f.text_area :note, class: "form-control" %><br>
          </p>
            <%= f.submit "Add Note", class: "btn btn-primary" %>
      </div>
            <% end %>
    </div> <!--Close notesSubmit div-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GardenNotesApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%=flash[:success]%>
<%= yield %>

</body>
</html>

app/views/notes/edit.html.erb
edit notes page

app/views/notes/index.html.erb
notes index page

app/views/notes/new.html.erb
notes new page

app/views/notes/show.html.erb
notes show page

app/views/welcome/index.html.erb
    <head>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script>
      $(document).ready(function(){
        //$(".btn1").click(function(){
        //    $("p").slideUp();
        //});
        $(".SignIn").click(function(){
            $(".col-sm-12").slideDown();
        });
      });
    </script>
    </head>

    <div class="header navbar-fixed-top">
    <h3>The Zukini</h3>
        <ul class="nav navbar-nav pull-right">
        <li class= "SignIn"> Sign In</li>
        <li><%= link_to "Sign up", sign_up_path %></li>
        </ul>
    </div>

    <%= form_tag sign_in_path do %>

    <div class="col-sm-12">
      <div class="well col-md-5 col-sm-offset-3">
        <div class="form-group Welcome-index-font">
          <h2 class = "page-header">Lets Get Growing!</h2>
        </div>
          <div class="form-horizontal">

       <div class="form-group"></div>
         <%= label_tag :email, "Email", class: "pull-left control-label" %>
         <div class="col-md-4"></div>
          <%= email_field_tag :email,"", autofocus: true, class: "col-sm-12 form-control" %>



       <div class="form-group"></div>
         <%= label_tag :password,"Password", class: "pull-left control-label" %>
         <div class="col-md-4"></div>
          <%= password_field_tag :password,"",class: "col-sm-12 form-control" %>



               <div class="form-group">
                 <div class="col-sm-6 pull-left"><br>
                   <%= submit_tag "Sign In", class: "btn btn-default"%>
                 </div>
               </div>

          <% end %>
          </div>
        </div>
      </div>
    </div>

<div class="mainCenter">
    <p>
      <div class="Welcome-index-font">
        <h2> Top Tips for April</h2>
        <hr>
      </div>

       <div class="Welcome-index-font">
         <h3>1. Use Compost</h3>
       </div>
        <br>
      Spread it around plants to ward off disease; put a bit in your potting mix to add slow-release micronutrients; top-dress beds with it to improve soil structure no matter what kind of soil you have; use it to help restore life to soil that's exhausted from years of chemical abuse. Sprinkle it on the lawn spring and fall to encourage the shallow grass roots... It's almost impossible to use too much.
      </p>

     <p>
       <div class="Welcome-index-font">
        <h3>2. Plant Crops in Wide Beds</h3>
       </div>
        <br>
      Crops are anything planted for harvesting: vegetables, cutting flowers, shrubs on hold to be transplanted... keeping these grouped as tightly as possible in beds that are not trod upon cuts down on weeding, conserves water, allows the compost to be concentrated where it will do the most good and improves soil structure year upon year as the layers of organic matter pile up. These beds are frequently raised or at least corralled neatly by boards or — I saw it once and am still impressed all these years later — by long slabs of granite. Aesthetics aside, the primary virtue of this tidiness is easier path maintenance. From the soil and plant point of view it's the special treatment that matters.
     </p>

      <p>
        <div class="Welcome-index-font">
         <h3>3. Mulch</h3>
        </div>

        <br>
        Mulch clothes the soil in a protective barrier that moderates temperature, conserves water, helps keep soil-borne diseases from splashing up and helps keep soil itself from splashing up — on your lettuce, for instance. Almost any organic mulch that will rot down into the soil is almost always preferable to landscape fabric with some kind of icing, but choosing the right mulch for each job is worth the extra effort.
        Straw for instance is inexpensive, but it's untidy compared to wood chips and it breaks down a lot faster. That suits straw to the vegetable patch while the chips win under shrubs. (The specialized mulches for warming soil and/or reflecting back just the right light upon your vegetables are seldom biodegradable. My experiments with them are ongoing so all I can say at this point is: Remember that they work only when light falls on them; the more your garden resembles a jungle — no names, please — the less effective they will be.)
      </p>

      <p>
      <div class="Welcome-index-font">
       <h3>4. Feed the Soil, Not the Plants</h3>
      </div>
      <br>
      Short version: Junk food, including organic junk food, has plenty of calories and may include added vitamins. But it's not great long-term nourishment, for many reasons we've learned and others we can so far only observe. Our bodies know the difference between eating a carrot and taking a capsule of vitamin A. Same deal with the soil.
      Longer version: Plant health depends on healthy roots; healthy roots depend on healthy soil for air, water and nutrients delivered in forms plants can use. Soil rich in organic matter — compost! — is generally rich in nutrients and in the teeming life (fungi, bacteria, worms, etc.) that makes those nutrients available to the plants.
      Ornamental plants in good soil seldom need added fertilizer, and crop plants that do need extra food need less of it when it's released slowly by friendly soil from things like rock powders, kelp and green manures. For an example of how this works with nitrogen, one of the most important nutrients, here's a Rodale Institute Research Report.
    </p>

    <p>
      <div class="Welcome-index-font">
       <h3>5. Share Something</h3>
      </div>
      <br>
      If you've got a garden, you're rich.
      Got seeds? The Seed Savers Exchange isn't just about vegetables; there's an affiliated Flower and Herb exchange, too. Got flowers? Hospitals won't take them anymore (allergies), but group homes, soup kitchens and — why not? — your neighborhood hardware store might be delighted with a bit of brightening up. Got produce? There's a national umbrella campaign for vegetable gardeners who want to plant a row for the hungry, and many food banks, farmers' markets and community gardens have set up organized donations. But there's no law that says you can't just give your extra beans to anyone who genuinely wants them. Hunger isn't always physical.
      The garden itself is worth sharing too. Garden tours are popular fundraisers so if you're up for the attendant stress, it's likely there's a cause that's looking for locations. In my experience with these things there's always a lot more preparation than I've allowed for... but also a lot more given back in new friends, new ideas and gazillions of pats.
    </p>

    <p>
      <div class="Welcome-index-font">
        <h3>6. Be There</h3>
     </div>
      <br>
      Whether Lao-Tse actually said it or not, it's true: The best fertilizer is the shadow of the gardener.</p>
    </p>

    <div class="Welcome-index-font">
    <div class="detailBox">
        <div class="titleBox">
          <label>Lets hear from you!</label>
            <button type="button" class="close" aria-hidden="true">&times;</button>
        </div>
        <div class="commentBox">

            <p class="taskDescription">Wonderful interface, it's like, the best ever. gorgeous.</p>
        </div>
        <div class="actionBox">
            <ul class="commentList">
                <li>
                    <div class="commenterImage">
                      <img src="http://lorempixel.com/50/50/people/6" />
                    </div>
                    <div class="commentText">
                        <p class="">I've been keeping my gardening notes organized with The Zukini for 5 years, I love it!</p> <span class="date sub-text">on March 5th, 2014</span>

                    </div>
                </li>
                <li>
                    <div class="commenterImage">
                      <img src="http://lorempixel.com/50/50/people/7" />
                    </div>
                    <div class="commentText">
                        <p class="">Hello this is a new user and I have to say, I could go on and on and on about this site.</p> <span class="date sub-text">on March 5th, 2014</span>

                    </div>
                </li>
                <li>
                    <div class="commenterImage">
                      <img src="http://lorempixel.com/50/50/people/9" />
                    </div>
                    <div class="commentText">
                        <p class="">Awesome! All my friends use it, too.</p> <span class="date sub-text">on March 5th, 2014</span>

                    </div>
                </li>
            </ul>
            <form class="form-inline" role="form">
                <div class="form-group">
                    <input class="form-control" type="text" placeholder="Your comments" />
                </div>
                <div class="form-group">
                    <button class="btn btn-default">Add</button>
                </div>
            </form>
        </div>
    </div>

  </div>
</div>